apiVersion: v1
kind: ServiceAccount
metadata:
  name: builder-image-registry-sa
  namespace: kpack
secrets:
- name: builder-image-registry-credentials
imagePullSecrets:
- name: builder-image-registry-credentials
---
apiVersion: kpack.io/v1alpha2
kind: ClusterStore
metadata:
  name: default
spec:
  sources:
  - image: gcr.io/paketo-buildpacks/java
---
apiVersion: kpack.io/v1alpha2
kind: ClusterStack
metadata:
  name: base
spec:
  id: "io.buildpacks.stacks.bionic"
  buildImage:
    image: "paketobuildpacks/build:base-cnb"
  runImage:
    image: "paketobuildpacks/run:base-cnb"
---
apiVersion: kpack.io/v1alpha2
kind: ClusterBuilder
metadata:
  name: default
spec:
  tag: BUILDER-TAG
  stack:
    name: base
    kind: ClusterStack
  store:
    name: default
    kind: ClusterStore
  serviceAccountRef:
    name: builder-image-registry-sa
    namespace: kpack
  order:
  - group:
    - id: paketo-buildpacks/java
